name: todomvc
version: 0.0.0
description: 
author:
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular2: '^2.0.0-alpha.37'
  browser: '^0.10.0+2'
  dart_to_js_script_rewriter: '^0.1.0+3'
  uuid: '^0.5.0'
transformers:
- dart_to_js_script_rewriter
- angular2:
    entry_points: web/main.dart
